# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/bank_accounts' do
  # This should return the minimal set of attributes required to create a valid
  # BankAccount. As you add validations to BankAccount, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      BankAccount.create! valid_attributes
      get bank_accounts_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      bank_account = BankAccount.create! valid_attributes
      get bank_account_url(bank_account)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_bank_account_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      bank_account = BankAccount.create! valid_attributes
      get edit_bank_account_url(bank_account)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new BankAccount' do
        expect do
          post bank_accounts_url, params: { bank_account: valid_attributes }
        end.to change(BankAccount, :count).by(1)
      end

      it 'redirects to the created bank_account' do
        post bank_accounts_url, params: { bank_account: valid_attributes }
        expect(response).to redirect_to(bank_account_url(BankAccount.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new BankAccount' do
        expect do
          post bank_accounts_url, params: { bank_account: invalid_attributes }
        end.not_to change(BankAccount, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post bank_accounts_url, params: { bank_account: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested bank_account' do
        bank_account = BankAccount.create! valid_attributes
        patch bank_account_url(bank_account), params: { bank_account: new_attributes }
        bank_account.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the bank_account' do
        bank_account = BankAccount.create! valid_attributes
        patch bank_account_url(bank_account), params: { bank_account: new_attributes }
        bank_account.reload
        expect(response).to redirect_to(bank_account_url(bank_account))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        bank_account = BankAccount.create! valid_attributes
        patch bank_account_url(bank_account), params: { bank_account: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested bank_account' do
      bank_account = BankAccount.create! valid_attributes
      expect do
        delete bank_account_url(bank_account)
      end.to change(BankAccount, :count).by(-1)
    end

    it 'redirects to the bank_accounts list' do
      bank_account = BankAccount.create! valid_attributes
      delete bank_account_url(bank_account)
      expect(response).to redirect_to(bank_accounts_url)
    end
  end
end
