# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/declares' do
  # This should return the minimal set of attributes required to create a valid
  # Declare. As you add validations to Declare, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Declare.create! valid_attributes
      get declares_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      declare = Declare.create! valid_attributes
      get declare_url(declare)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_declare_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      declare = Declare.create! valid_attributes
      get edit_declare_url(declare)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Declare' do
        expect do
          post declares_url, params: { declare: valid_attributes }
        end.to change(Declare, :count).by(1)
      end

      it 'redirects to the created declare' do
        post declares_url, params: { declare: valid_attributes }
        expect(response).to redirect_to(declare_url(Declare.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Declare' do
        expect do
          post declares_url, params: { declare: invalid_attributes }
        end.not_to change(Declare, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post declares_url, params: { declare: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested declare' do
        declare = Declare.create! valid_attributes
        patch declare_url(declare), params: { declare: new_attributes }
        declare.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the declare' do
        declare = Declare.create! valid_attributes
        patch declare_url(declare), params: { declare: new_attributes }
        declare.reload
        expect(response).to redirect_to(declare_url(declare))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        declare = Declare.create! valid_attributes
        patch declare_url(declare), params: { declare: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested declare' do
      declare = Declare.create! valid_attributes
      expect do
        delete declare_url(declare)
      end.to change(Declare, :count).by(-1)
    end

    it 'redirects to the declares list' do
      declare = Declare.create! valid_attributes
      delete declare_url(declare)
      expect(response).to redirect_to(declares_url)
    end
  end
end
