# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/memo_categories' do
  # This should return the minimal set of attributes required to create a valid
  # MemoCategory. As you add validations to MemoCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      MemoCategory.create! valid_attributes
      get memo_categories_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      memo_category = MemoCategory.create! valid_attributes
      get memo_category_url(memo_category)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_memo_category_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      memo_category = MemoCategory.create! valid_attributes
      get edit_memo_category_url(memo_category)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new MemoCategory' do
        expect do
          post memo_categories_url, params: { memo_category: valid_attributes }
        end.to change(MemoCategory, :count).by(1)
      end

      it 'redirects to the created memo_category' do
        post memo_categories_url, params: { memo_category: valid_attributes }
        expect(response).to redirect_to(memo_category_url(MemoCategory.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new MemoCategory' do
        expect do
          post memo_categories_url, params: { memo_category: invalid_attributes }
        end.not_to change(MemoCategory, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post memo_categories_url, params: { memo_category: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested memo_category' do
        memo_category = MemoCategory.create! valid_attributes
        patch memo_category_url(memo_category), params: { memo_category: new_attributes }
        memo_category.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the memo_category' do
        memo_category = MemoCategory.create! valid_attributes
        patch memo_category_url(memo_category), params: { memo_category: new_attributes }
        memo_category.reload
        expect(response).to redirect_to(memo_category_url(memo_category))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        memo_category = MemoCategory.create! valid_attributes
        patch memo_category_url(memo_category), params: { memo_category: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested memo_category' do
      memo_category = MemoCategory.create! valid_attributes
      expect do
        delete memo_category_url(memo_category)
      end.to change(MemoCategory, :count).by(-1)
    end

    it 'redirects to the memo_categories list' do
      memo_category = MemoCategory.create! valid_attributes
      delete memo_category_url(memo_category)
      expect(response).to redirect_to(memo_categories_url)
    end
  end
end
