# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/patners' do
  # This should return the minimal set of attributes required to create a valid
  # Patner. As you add validations to Patner, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Patner.create! valid_attributes
      get patners_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      patner = Patner.create! valid_attributes
      get patner_url(patner)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_patner_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      patner = Patner.create! valid_attributes
      get edit_patner_url(patner)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Patner' do
        expect do
          post patners_url, params: { patner: valid_attributes }
        end.to change(Patner, :count).by(1)
      end

      it 'redirects to the created patner' do
        post patners_url, params: { patner: valid_attributes }
        expect(response).to redirect_to(patner_url(Patner.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Patner' do
        expect do
          post patners_url, params: { patner: invalid_attributes }
        end.not_to change(Patner, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post patners_url, params: { patner: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested patner' do
        patner = Patner.create! valid_attributes
        patch patner_url(patner), params: { patner: new_attributes }
        patner.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the patner' do
        patner = Patner.create! valid_attributes
        patch patner_url(patner), params: { patner: new_attributes }
        patner.reload
        expect(response).to redirect_to(patner_url(patner))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        patner = Patner.create! valid_attributes
        patch patner_url(patner), params: { patner: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested patner' do
      patner = Patner.create! valid_attributes
      expect do
        delete patner_url(patner)
      end.to change(Patner, :count).by(-1)
    end

    it 'redirects to the patners list' do
      patner = Patner.create! valid_attributes
      delete patner_url(patner)
      expect(response).to redirect_to(patners_url)
    end
  end
end
