# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/payout_channels' do
  # This should return the minimal set of attributes required to create a valid
  # PayoutChannel. As you add validations to PayoutChannel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      PayoutChannel.create! valid_attributes
      get payout_channels_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      payout_channel = PayoutChannel.create! valid_attributes
      get payout_channel_url(payout_channel)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_payout_channel_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      payout_channel = PayoutChannel.create! valid_attributes
      get edit_payout_channel_url(payout_channel)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new PayoutChannel' do
        expect do
          post payout_channels_url, params: { payout_channel: valid_attributes }
        end.to change(PayoutChannel, :count).by(1)
      end

      it 'redirects to the created payout_channel' do
        post payout_channels_url, params: { payout_channel: valid_attributes }
        expect(response).to redirect_to(payout_channel_url(PayoutChannel.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new PayoutChannel' do
        expect do
          post payout_channels_url, params: { payout_channel: invalid_attributes }
        end.not_to change(PayoutChannel, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post payout_channels_url, params: { payout_channel: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested payout_channel' do
        payout_channel = PayoutChannel.create! valid_attributes
        patch payout_channel_url(payout_channel), params: { payout_channel: new_attributes }
        payout_channel.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the payout_channel' do
        payout_channel = PayoutChannel.create! valid_attributes
        patch payout_channel_url(payout_channel), params: { payout_channel: new_attributes }
        payout_channel.reload
        expect(response).to redirect_to(payout_channel_url(payout_channel))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        payout_channel = PayoutChannel.create! valid_attributes
        patch payout_channel_url(payout_channel), params: { payout_channel: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested payout_channel' do
      payout_channel = PayoutChannel.create! valid_attributes
      expect do
        delete payout_channel_url(payout_channel)
      end.to change(PayoutChannel, :count).by(-1)
    end

    it 'redirects to the payout_channels list' do
      payout_channel = PayoutChannel.create! valid_attributes
      delete payout_channel_url(payout_channel)
      expect(response).to redirect_to(payout_channels_url)
    end
  end
end
